version: '2.0'
services:
  pg-0:
    image: shawoo/postgres:11-repmgr
    ports:
      - 5432
    volumes:
      - ./pg0:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=axelor
      - POSTGRESQL_USERNAME=axelor
      - POSTGRESQL_PASSWORD=axelor
      - POSTGRESQL_DATABASE=axelor
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-1,pg-0
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
  pg-1:
    image: shawoo/postgres:11-repmgr
    ports:
      - 5432
    volumes:
      - ./pg1:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=axelor
      - POSTGRESQL_USERNAME=axelor
      - POSTGRESQL_PASSWORD=axelor
      - POSTGRESQL_DATABASE=axelor
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
  postgresdb:
    image: shawoo/pgpool:4
    restart: always
    ports:
      - 5432
    depends_on:
      - pg-0
      - pg-1
    links:
      - pg-0
      - pg-1
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=axelor
      - PGPOOL_SR_CHECK_PASSWORD=axelor
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=axelor
      - PGPOOL_POSTGRES_PASSWORD=axelor
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=axelor
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    #healthcheck:
    #  test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    links:
      - postgresdb
    ports:
      - "5678:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@163.com
      - PGADMIN_DEFAULT_PASSWORD=xxxxyyyyzzzz
